name: Lint and Fix PHP code style

on:
  push:
    branches: [ main ]
    paths: ['**.php']
  pull_request:
    branches: [ main ]
    paths: ['**.php']

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.2.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(auto-lint): Fix PHP code style issues"